/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cs.ia;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import java.awt.print.PrinterException;
import java.time.LocalDate;
import java.time.temporal.ChronoUnit;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author zoepa
 */
public class payment extends javax.swing.JFrame {
    int pot = 0;
    /**
     * Creates new form payment
     */
    public payment() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        crea = new javax.swing.JButton();
        exit = new javax.swing.JButton();
        previous = new javax.swing.JButton();
        cstID = new javax.swing.JTextField();
        clear = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        payPan = new javax.swing.JTextArea();
        print = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        key = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 800));
        getContentPane().setLayout(null);

        jLabel6.setBackground(new java.awt.Color(51, 255, 255));
        jLabel6.setFont(new java.awt.Font("SignPainter", 1, 24)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Dekyil Guest House");
        jLabel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 255, 153)));
        getContentPane().add(jLabel6);
        jLabel6.setBounds(0, 0, 730, 76);

        jLabel1.setFont(new java.awt.Font("Heiti SC", 0, 14)); // NOI18N
        jLabel1.setText("Enter Customer ID");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 91, 135, 38);

        crea.setText("Create Bill");
        crea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                creaActionPerformed(evt);
            }
        });
        getContentPane().add(crea);
        crea.setBounds(410, 550, 100, 24);

        exit.setText("Exit");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        getContentPane().add(exit);
        exit.setBounds(640, 550, 90, 24);

        previous.setText("Previous");
        previous.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                previousActionPerformed(evt);
            }
        });
        getContentPane().add(previous);
        previous.setBounds(520, 550, 110, 24);

        cstID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cstIDActionPerformed(evt);
            }
        });
        getContentPane().add(cstID);
        cstID.setBounds(147, 92, 139, 38);

        clear.setText("Clear");
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });
        getContentPane().add(clear);
        clear.setBounds(300, 550, 100, 24);

        payPan.setColumns(20);
        payPan.setRows(5);
        jScrollPane1.setViewportView(payPan);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(323, 93, 400, 450);

        print.setText("Print");
        print.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printActionPerformed(evt);
            }
        });
        getContentPane().add(print);
        print.setBounds(190, 550, 100, 24);

        jLabel3.setFont(new java.awt.Font("Heiti SC", 0, 14)); // NOI18N
        jLabel3.setText("Enter Key");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 160, 135, 39);

        key.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                keyActionPerformed(evt);
            }
        });
        getContentPane().add(key);
        key.setBounds(147, 161, 139, 39);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        System.exit(0); // TODO add your handling code here:
    }//GEN-LAST:event_exitActionPerformed

    private void previousActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_previousActionPerformed
        Function_Form fnc = new Function_Form();
        fnc.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_previousActionPerformed

    private void creaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_creaActionPerformed
        try{
            search1 srch = new search1();
            srch.search(Integer.parseInt(cstID.getText()));
            Class.forName("org.sqlite.JDBC");
            String url = "jdbc:sqlite:/Users/zoepa/NetBeansProjects/CS IA/Database/hotel.db";
            Connection conn = DriverManager.getConnection(url);
            conn.setAutoCommit(false);
            Statement stmt = conn.createStatement();
            ResultSet query = stmt.executeQuery("SELECT * FROM customer WHERE cstID ="+cstID.getText()+"");
            String chkInDt = query.getString(6);
            String chkOutDt = query.getString(7);
            DateFormat df = new SimpleDateFormat("dd/MM/yyyy");
            Date dteBf = df.parse(chkInDt);
            Date dteAf = df.parse(chkOutDt);
            int noRooms = (query.getInt(5));
            long difference = dteAf.getTime() - dteBf.getTime();
            System.out.print(difference);
            System.out.print(dteBf);
            System.out.print(dteAf);
            float days = (difference / (1000*60*60*24));
            System.out.print(days);
            float price = noRooms * 1500*days;
            System.out.print(price);
            //long noOfDaysBetween;
            //noOfDaysBetween = ChronoUnit.DAYS.between(dteBf,dteAf);
            //while (calendar.getTime().before(dteAf))
            //{
              //  Date result = calendar.getTime();
              //  dates.add(result);
              //  calendar.add(Calendar.DATE, 1);
            //}
            payPan.append("\t\t Dekyil Guest House \n\n "
                    +"\n==========================================\n"
                    +"Customer ID: "+cstID.getText()+
                    "\n Key: "+query.getInt(1)+ "\n Name: "+query.getString(3)+"\n Number Of Guest: "+query.getInt(4)+"\n Number of Rooms: "+query.getInt(5)+"\n Check In Date: "+query.getString(6)+"\n Check Out Date"+query.getString(7)+"\n Number of Days:"+days+"\n Total Fee:"+price+"");  
            
            conn.close();
        }
        catch(Exception e){
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Somthing went wrong!");
        }
            // TODO add your handling code here:
    }//GEN-LAST:event_creaActionPerformed

    private void cstIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cstIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cstIDActionPerformed

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
        payPan.setText("");
        cstID.setText("");
        // TODO add your handling code here:
    }//GEN-LAST:event_clearActionPerformed

    private void printActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printActionPerformed
        try {
            payPan.print();        // TODO add your handling code here:
        } catch (PrinterException ex) {
            Logger.getLogger(payment.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_printActionPerformed

    private void keyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_keyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_keyActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new payment().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton clear;
    private javax.swing.JButton crea;
    private javax.swing.JTextField cstID;
    private javax.swing.JButton exit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField key;
    private javax.swing.JTextArea payPan;
    private javax.swing.JButton previous;
    private javax.swing.JButton print;
    // End of variables declaration//GEN-END:variables
}
